"""empty message

Revision ID: 4cddf8bc026a
Revises: 
Create Date: 2018-05-04 09:12:51.830429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cddf8bc026a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chname', sa.String(length=64), nullable=True),
    sa.Column('enname', sa.String(length=64), nullable=True),
    sa.Column('director', sa.String(length=64), nullable=True),
    sa.Column('leadingRole', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('screeningmodel', sa.String(length=8), nullable=True),
    sa.Column('openday', sa.Date(), nullable=True),
    sa.Column('backgroundpicture', sa.String(length=256), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('passwd', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('cinemaid', sa.Integer(), nullable=True),
    sa.Column('screentype', sa.String(length=4), nullable=True),
    sa.Column('soundtype', sa.String(length=8), nullable=True),
    sa.Column('seatnum', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaid'], ['cinemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallschedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.Column('pricetype', sa.Integer(), nullable=True),
    sa.Column('price0', sa.Float(), nullable=True),
    sa.Column('price1', sa.Float(), nullable=True),
    sa.Column('price2', sa.Float(), nullable=True),
    sa.Column('showdate', sa.Date(), nullable=True),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaid'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallid'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('seattype', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaid'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallid'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=16), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.Column('cinemaid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('hallScheduleid', sa.Integer(), nullable=True),
    sa.Column('seatidlist', sa.String(length=16), nullable=True),
    sa.Column('pnum', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pstr', sa.String(length=16), nullable=True),
    sa.Column('createTime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('changeTime', sa.Time(), nullable=True),
    sa.Column('payTime', sa.Time(), nullable=True),
    sa.Column('getTime', sa.Time(), nullable=True),
    sa.Column('backTime', sa.Time(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaid'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallScheduleid'], ['hallschedules.id'], ),
    sa.ForeignKeyConstraint(['hallid'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.account'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seatschedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('seatid', sa.Integer(), nullable=True),
    sa.Column('hallScheduleid', sa.Integer(), nullable=True),
    sa.Column('orderid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaid'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallScheduleid'], ['hallschedules.id'], ),
    sa.ForeignKeyConstraint(['hallid'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['orderid'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seatid'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seatschedules')
    op.drop_table('orders')
    op.drop_table('seats')
    op.drop_table('hallschedules')
    op.drop_table('halls')
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
