# -*- coding:utf-8 -*-
from tpp.models.movie import Movie
from tpp.models.cinema import Cinema
from tpp.models.hall import Hall
from tpp.models.hallSchedule import HallSchedule
from tpp.models.user import User
from tpp.models.seat import Seat
from tpp.models.order import Order
from tpp.models.seatSchedule import SeatSchedule